resolver: lts-18.2
packages:
- .
ghc-options:
  "$locals": -fwrite-ide-info
extra-deps:
- git: https://github.com/pankzsoft/servant-server-base.git
  commit: 6ad315372262aba52df07b577eb2a965458861c6
allow-newer: true
