resolver: lts-18.13
packages:
- .
ghc-options:
  "$locals": -fwrite-ide-info
extra-deps:
- git: https://github.com/pankzsoft/servant-server-base.git
  commit: 2a4469f708862293b5ddfb9ffede3141c2631d4e
allow-newer: true
