version: '3'
services:
  nginx-web:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./:/etc/nginx/conf.d
  auth:
    image: pankzsoft/hsauth:latest
    container_name: auth
    restart: always
    environment:
      AUTH_SERVER_ADMIN_PASSWORD: password
      # This key is used only for testing purposes, so fine to put under
      # version control. Real production code will have key injected from
      # deployment process
      AUTH_SERVER_JWK: ${AUTH_SERVER_JWK}
    ports:
    - 3001:3001
    volumes:
    - auth-data:/home/user
  sensei:
    image: pankzsoft/sensei:latest
    restart: always
    container_name: sensei
    environment:
      # This has to be consistent with how the service is named in nginx.conf
      # because the `Host` header is set
      SENSEI_SERVER_NAME: "sensei:8899"
      SENSEI_SERVER_PORT: 8899
      ENVIRONMENT: prod
    ports:
      - 8899:8899
    volumes:
      - sensei-data:/home/user
volumes:
  sensei-data: {}
  auth-data: {}
